"""add agent_outputs to chat_messages

Revision ID: fbb5b95162fc
Revises: 4a1fd58090ed
Create Date: 2026-03-02 19:58:47.129667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fbb5b95162fc'
down_revision: Union[str, None] = '4a1fd58090ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('agent_outputs', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'agent_outputs')
    # ### end Alembic commands ###
